### ISSUE TITLE
Create project layout

### ISSUE THREAD

**Issue by pavlov-tony** [pavlov-tony/xproject#1]
Acceptance criteria:
- Add router with all endpoints from swagger specs.
- Add dummy handlers.
- Add handler which response with swagger specs at root path `/api/v1`
- All paths should have prefix `/api/v1`

**Comment by pavlov-tony** [comment]
Please use that guide: https://github.com/golang-standards/project-layout

**Comment by pavlov-tony** [comment]
https://github.com/buaazp/fasthttprouter

**Comment by qezz** [comment]
The unresolved questions:

1. Compliance with the spec 
2. `/api/openapi-spec/swagger.json` vs `/api/swagger-spec/swagger.json`. [Some sources](https://swagger.io/blog/difference-between-swagger-and-openapi/) define swagger-spec as a specification for swagger tools, but openapi-spec as a product of the swagger tools.
3. Need to define the paths (absolute or relative) to static files (e.g. `/api/openapi-spec/swagger.json`). Depends on deployment hierarchy.
4. Define the need of the functionality to update the instance data. For example, it could be `PUT /instance/{id}` (assuming that adding a new instance looks like `POST /instance/`)
5. Which port to listen? For now it's "8080"

**Comment by pavlov-tony** [comment]
I swear that will start tomorrow from your commit and questions.
