### ISSUE TITLE
Add Dockerfile and docker-compose.yml to project

### ISSUE THREAD

**Issue by pavlov-tony** [pavlov-tony/xproject#6]
Acceptance criteria:
- Add Dockerfile.
- Add docker-compose.yml.

**Comment by irodionr** [comment]
For issues #9 and #10 we are using PostgreSQL, so it needs to be added into the Docker container.

**Comment by pavlov-tony** [comment]
@irodionr did you mean docker-compose? It's a bad approach to add DB in the same container with app :)

**Comment by irodionr** [comment]
@pavlov-tony Yes, sorry, I meant docker-compose.
